# Configuración del sitio
url: "https://2624789.github.io/juanpablo.co"
baseurl: "/"

title: Juan Pablo Puentes Vargas
author: "2624789"
email: jp@juanpablo.co
phone: "+57(8) 8714193"
skype: "juanpablo.puentes"
description: >-
  Asesoría especializada en Derecho Informático (Tecnología) y  Propiedad Intelectual desde el sur de Colombia - Legal advice in IP & IT Law
keywords: "Abogado, Tecnología, Derecho Informático, Propiedad Intelectual, Derecho Comercial, Derecho Constitucional, Derecho Laboral, Neiva, Huila, software libre, licencias libres, Lawyer, legal advice, IT Law, intellectual property, Адвокат, юрист, Колумбия, Уила, Нейва, интеллектуальная собственность, Информационное право"
license: "CC-BY-SA"

social:
  - title: facebook
    url: https://www.facebook.com/JuanPabloPuentesV/
  - title: twitter
    url: https://twitter.com/JuanPabloPV
  - title: instagram
    url: https://instagram.com/juanpablopuentesv
  - title: youtube
    url: https://www.youtube.com/channel/UCEKqjLpvOjYXACWB5iQMHjg
  - title: envelope
    url: mailto:jp@juanpablo.co

github_username: "2624789"

# Configuración de compilación
markdown: kramdown
permalink: pretty
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed
